### ISSUE TITLE
Python requirement should be python>=3.7

### ISSUE THREAD

**Issue by INFCode** [hube12/DecompilerMC#25]
As the argument 'capture_output' of subprocess.run is added after python 3.7, when running this script on my python 3.6.4, it will throw an error as follows:
```
Traceback (most recent call last):
  File ".\main.py", line 650, in <module>
    main()
  File ".\main.py", line 580, in main
    remap(version, side, args.quiet)
  File ".\main.py", line 256, in remap
    ], check=True, capture_output=quiet)
  File "subprocess.py", line 403, in run
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```
Therefore this script should only work with python 3.7+, instead of the version of 3.5+ which is said in README.

**Comment by hube12** [comment]
Yeah, my bad, actually forgot to add that after the last issue on mac
